export const COURSES = [
  {
    slug: "egyptian-baladi-foundations",
    title: "Egyptian Baladi — Foundations",
    instructor: "Amara Nour",
    level: "Beginner",
    price: 59,
    originalPrice: 89,
    rating: "★★★★★",
    ratingValue: "4.9",
    reviewCount: 612,
    lessons: 24,
    duration: "6h 40m",
    letter: "B",
    desc: "Posture, isolations and the walk that anchors every style.",
    about:
      "This course lays the technical foundation for Egyptian Baladi — the social, earthy style underlying almost every Oriental dance vocabulary. No dance background required.",
    curriculum: [
      { title: "Posture & Grounding", time: "12:40", preview: true },
      { title: "The Egyptian Walk", time: "18:05" },
      { title: "Hip Isolations, Part 1", time: "22:30" },
      { title: "Ribcage & Chest Work", time: "21:47" },
    ],
  },
  {
    slug: "veil-work-stage-presence",
    title: "Veil Work & Stage Presence",
    instructor: "Leyla Marín",
    level: "Intermediate",
    price: 89,
    originalPrice: 120,
    rating: "★★★★★",
    ratingValue: "4.8",
    reviewCount: 340,
    lessons: 18,
    duration: "5h 10m",
    letter: "V",
    desc: "Choreograph flowing veil entrances for solo performance.",
    about:
      "Build a complete veil entrance from the ground up — carriage, fabric control, and the stagecraft that makes an audience lean in.",
    curriculum: [
      { title: "Choosing & Handling Your Veil", time: "10:12", preview: true },
      { title: "The Entrance Wrap", time: "16:40" },
      { title: "Floating Transitions", time: "19:05" },
      { title: "Exit & Reveal", time: "14:22" },
    ],
  },
  {
    slug: "drum-solo-choreography",
    title: "Drum Solo Choreography",
    instructor: "Dalia Rostam",
    level: "Advanced",
    price: 110,
    originalPrice: 140,
    rating: "★★★★☆",
    ratingValue: "4.7",
    reviewCount: 205,
    lessons: 21,
    duration: "7h 05m",
    letter: "D",
    desc: "Sharp accents and layered rhythm for competition-ready sets.",
    about:
      "Advanced accent work set to shifting tabla rhythms, built for dancers preparing a competition or showcase solo.",
    curriculum: [
      { title: "Reading the Rhythm", time: "15:30", preview: true },
      { title: "Sharp Accents, Part 1", time: "20:11" },
      { title: "Layered Combinations", time: "23:47" },
      { title: "Building Your 90-Second Solo", time: "18:02" },
    ],
  },
  {
    slug: "arm-hand-styling-essentials",
    title: "Arm & Hand Styling Essentials",
    instructor: "Farah Idris",
    level: "Beginner",
    price: 49,
    originalPrice: 65,
    rating: "★★★★★",
    ratingValue: "4.9",
    reviewCount: 480,
    lessons: 12,
    duration: "3h 20m",
    letter: "A",
    desc: "The details that separate graceful from generic.",
    about:
      "Finishing-school work for the arms and hands — the small adjustments that instantly read as trained rather than improvised.",
    curriculum: [
      { title: "Wrist & Finger Isolation", time: "9:40", preview: true },
      { title: "Arm Frames", time: "12:15" },
      { title: "Hands Through Turns", time: "13:52" },
    ],
  },
  {
    slug: "saidi-cane-dance",
    title: "Saidi & the Cane Dance",
    instructor: "Amara Nour",
    level: "Intermediate",
    price: 75,
    originalPrice: 95,
    rating: "★★★★☆",
    ratingValue: "4.6",
    reviewCount: 158,
    lessons: 16,
    duration: "4h 45m",
    letter: "S",
    desc: "Playful upper-Egyptian rhythm work with the assaya cane.",
    about:
      "A joyful, grounded style from Upper Egypt built around the assaya (cane) — playful, percussive, and a crowd favorite.",
    curriculum: [
      { title: "Cane Handling Basics", time: "11:20", preview: true },
      { title: "Saidi Rhythm & Weight", time: "17:35" },
      { title: "Cane Spins", time: "16:48" },
    ],
  },
  {
    slug: "five-minute-solo",
    title: "Building a 5-Minute Solo",
    instructor: "Leyla Marín",
    level: "Advanced",
    price: 120,
    originalPrice: 150,
    rating: "★★★★★",
    ratingValue: "4.9",
    reviewCount: 96,
    lessons: 20,
    duration: "6h 15m",
    letter: "5",
    desc: "Structure, staging and musicality for a showcase-ready set.",
    about:
      "Everything that goes into a performance-ready solo: musical phrasing, staging, costume considerations, and how to rehearse it into muscle memory.",
    curriculum: [
      { title: "Choosing Your Music", time: "14:10", preview: true },
      { title: "Structuring the Arc", time: "19:26" },
      { title: "Staging for a Room", time: "17:03" },
    ],
  },
];

export const INSTRUCTORS = [
  { name: "Amara Nour", city: "Cairo, Egypt", letter: "A" },
  { name: "Leyla Marín", city: "Barcelona, Spain", letter: "L" },
  { name: "Dalia Rostam", city: "Istanbul, Turkey", letter: "D" },
  { name: "Farah Idris", city: "Beirut, Lebanon", letter: "F" },
];

export function getCourseBySlug(slug) {
  return COURSES.find((c) => c.slug === slug);
}
